# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cul-fedora-arm}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Stuart"]
  s.date = %q{2009-08-26}
  s.description = %q{Tools for dealing with Cul ARM specification}
  s.email = %q{tastyhat@jamesstuart.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "cul-fedora-arm.gemspec",
     "lib/cul-fedora-arm.rb",
     "lib/cul/fedora/arm/builder.rb",
     "lib/cul/fedora/arm/tasks.rb",
     "test/cul_fedora_arm_builder_test.rb",
     "test/cul_fedora_arm_tasks_test.rb",
     "test/factories.rb",
     "test/fixtures/case1/builder-template-noheader.txt",
     "test/fixtures/case1/builder-template.txt",
     "test/helpers/template_builder.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/tastyhat/cul-fedora-arm}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Tools for dealing with Cul ARM specification}
  s.test_files = [
    "test/cul_fedora_arm_builder_test.rb",
     "test/factories.rb",
     "test/helpers/template_builder.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-fedora>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<ruby-fedora>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<thoughtbot-factory_girl>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<ruby-fedora>, [">= 0"])
  end
end
